type Mutation {
  createContactRequest(
    category: String!
    email: String!
    familyName: String!
    givenName: String!
    message: String!
    organization: String
    tel: String
  ): ContactRequest
}

type Query {
  readContactRequest(id: String!): ContactRequest
}

type ContactRequest {
  id: Cuid!
  category: String!
  email: EmailAddress!
  familyName: String!
  givenName: String!
  message: String!
  organization: String
  tel: PhoneNumber
  createdAt: DateTime!
}
