extend type Query {
  readBooking(paymentIntentId: String!): Booking
}

type Booking {
  id: Cuid!
  paymentIntentId: String!
  datetime: DateTime!
  firstName: String!
  lastName: String!
  organization: String!
  organizationTitle: String!
  email: String!
  tel: String!
  createdAt: DateTime!
}
