extend type Mutation {
  createBooking(
    datetime: DateTime!
    firstName: String!
    lastName: String!
    organization: String!
    organizationTitle: String!
    email: String!
    tel: String!
  ): Booking
}

type Booking {
  id: Cuid!
  datetime: DateTime!
  firstName: String!
  lastName: String!
  organization: String!
  organizationTitle: String!
  email: String!
  tel: String!
  createdAt: DateTime!
}
