extend type Mutation {
  createCustomer(
    firsName: String!
    lastName: String!
    organization: String!
    organizationTitle: String!
    email: String!
    tel: String!
  ): Customer!

  createPaymentIntent: PaymentIntent!
}

type Customer {
  id: Cuid!
  firsName: String!
  lastName: String!
  organization: String!
  organizationTitle: String!
  email: String!
  tel: String!
  createdAt: DateTime!
}

type PaymentIntent {
  clientSecret: String
}
